add find-by-date option
Closes #9.

diff --git a/dr b/dr
--- a/dr
+++ b/dr
@@ -560,6 +560,26 @@ dreamfind() {
             newargs=$DREAMGLOB
             ;;
 
+        "date"|"d")
+            [ -n "$2" ] || die "oops"
+            [ -n "$3" ] || die "oops"
+            operator=$2
+            dateExpr=$3
+            [[ "$dateExpr" =~ [012][0-9][0-9][0-9]-[01][0-9]-[0123][0-9] ]] || die "Invalid date (use YYYY-MM-DD)."
+            case $operator in
+                'gt'|'>')        awkop='>' ;;
+                'lt'|'<')        awkop='<' ;;
+                'ge'|'>=')       awkop='>=' ;;
+                'le'|'<=')       awkop='<=' ;;
+                'eq'|'='|'==')   awkop='==' ;;
+                'ne'|'!='|'<>')  awkop='!=' ;;
+                *)               die "Invalid operator!" ;;
+            esac
+
+            newargs=$(awk "/Date:	/ { if (\$2 $awkop \"$dateExpr\") { print FILENAME } }" $DREAMGLOB)
+            shift 2
+            ;;
+
         "tagged"|"t")
             local usage="Usage: dr $action tagged [-f] <header regex> <value regex>"
             [ -n "$2" ] || die "$usage"
